import type { Metadata } from "next";
import { Rubik, Afacad_Flux } from "next/font/google";
import "./globals.css";
import { Menu } from "@/components/Menu";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

const afacadFlux = Afacad_Flux({
  variable: "--font-afacad-flux",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${afacadFlux.variable} antialiased`}
      >
        <Menu />
        {children}
      </body>
    </html>
  );
}
